openapi: 3.1.0
info:
  version: 1.0.0
  title: News blog
  contact:
    email: contact@example.com
    url: "https://github.com/essserrr/news-blog"
  description:
    $ref: ./info-description.md
tags:
  - name: Echo
    description: Example echo operations.
  - name: Tag
    description: Operations about tags.
  - name: Tag1
    description: This is a tag description.
servers:
  - url: "https://{tenant}/api/v1"
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: "https://example.com/api/v1"
paths:
  "/tags/{tag_id}":
    $ref: "paths/tags_{tag_id}.yaml"
  /echo:
    $ref: paths/echo.yaml
  /pathItem:
    $ref: paths/path-item.yaml
  /pathItemWithExamples:
    $ref: paths/path-item-with-examples.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "http://example.com/api/oauth/dialog"
          scopes:
            "read:users": read users info
            "write:users": modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
