openapi: 3.1.0
info:
  version: 1.0.1
  title: News blog
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/
  contact:
    url: "https://github.com/essserrr/news-blog"
  description:
    $ref: ./info-description.md
servers:
  - url: "https://localhost:8000"
paths:
  "/tags":
    $ref: "paths/tag.yaml"
  "/tags/{tag_id}":
    $ref: "paths/tag_{tag_id}.yaml"

  "/categories":
    $ref: "paths/category.yaml"
  "/categories/{category_id}":
    $ref: "paths/category_{category_id}.yaml"

  "/users/{user_id}":
    $ref: "paths/user_{user_id}.yaml"

  "/authors":
    $ref: "paths/author.yaml"
  "/authors/{author_id}":
    $ref: "paths/author_{author_id}.yaml"

  "/auth/{user_username}":
    $ref: "paths/auth_{user_username}.yaml"

  "/comments/{news_id}":
    $ref: "paths/comment_{news_id}.yaml"

  "/news":
    $ref: "paths/news.yaml"
  "/news/{news_id}":
    $ref: "paths/news_{news_id}.yaml"

  "/drafts":
    $ref: "paths/draft.yaml"
  "/drafts/{news_id}":
    $ref: "paths/draft_{news_id}.yaml"
  "/drafts/{news_id}/publish":
    $ref: "paths/draft_{news_id}_publish.yaml"
