openapi: 3.1.0
info:
  version: 1.0.1
  title: News blog
  contact:
    url: "https://github.com/essserrr/news-blog"
  description:
    $ref: ./info-description.md
servers:
  - url: "https://localhost:8000/"
paths:
  "/tags?offset={offset}&limit={limit}":
    $ref: "paths/tags.yaml"
  "/tags/{tag_name}":
    $ref: "paths/tags_{tag_name}.yaml"
  "/tags/{tag_id}":
    $ref: "paths/tags_{tag_id}.yaml"
